### ISSUE TITLE
NTR: Request for S12 claspers

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#10]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>claspers <p><b>Definition</b><p> Pair of appendages under the abdomen of male cartilaginous fishes like sharks or rays, or at the end of the abdomen of a male insect, used to hold the female during copulation.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://en.wikipedia.org/wiki/Clasper and other online resources; adapted from<p> <b>Mapping to other terminologies </b><p> http://purl.obolibrary.org/obo/UBERON_0010516 (sameAs)<p>

**Comment by roswri** [comment]
Term created:
Made singular as per advice in new S12 SQL menu.

S1267 - clasper: An appendage, usually paired, under the abdomen of male cartilaginous fishes like sharks or rays, or at the end of the abdomen of a male insect, used to hold the female during copulation.
