### ISSUE TITLE
NTR: Request for S12 lower rostrum

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#11]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>lower rostrum <p><b>Definition</b><p> The lower part of a two-part organism’s beak or beak-like projecting structure. The term is used in reference to cetaceans, crustaceans, cephalopods and some fishes.<p><H2> Optional </H2><p><b>Sources/references</b><p> adapted from https://en.wikipedia.org/wiki/Rostrum_(anatomy) and other online resources<p>

**Comment by roswri** [comment]
Term created:
S1268 - lower rostrum: The lower part of an organism's two-part beak or beak-like projecting structure. The term is used in reference to cetaceans, crustaceans, cephalopods and some fishes.
