### ISSUE TITLE
NTR: Request for S12 upper rostrum

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#12]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>upper rostrum <p><b>Definition</b><p> The upper part of a two-part organism’s beak or beak-like structure. The term is used in reference to cetaceans, crustaceans, cephalopods and some fishes.<p><H2> Optional </H2><p>

**Comment by roswri** [comment]
Term created:
S1269 - upper rostrum: The upper part of an organism's two-part beak or beak-like projecting structure. The term is used in reference to cetaceans, crustaceans, cephalopods and some fishes.
