### ISSUE TITLE
NTR: Request for S12 head

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#13]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>head <p><b>Definition</b><p> The cephalic part of an organism, usually located at one end of the body, which contains the highest density of neurons, and often other sense organs.<p><H2> Optional </H2><p>

**Comment by roswri** [comment]
Term created:
S1270 - head: The cephalic part of an organism, usually located at one end of the body, which contains the highest density of neurons, and often other sense organs.
