### ISSUE TITLE
NTR: Request for S12 prosome

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#14]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>prosome <p><b>Definition</b><p> The anterior of the two or three main divisions of the body of certain invertebrates.<p><H2> Optional </H2><p>

**Comment by roswri** [comment]
Term created:
S1271 - prosome: The anterior of the two or three main divisions of the body of certain invertebrates.
