### ISSUE TITLE
NTR: Request for S12 metasome

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#15]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>metasome <p><b>Definition</b><p> The posterior of the two or three main divisions of the body of certain invertebrates.<p><H2> Optional </H2><p>

**Comment by roswri** [comment]
Term created:
S1272 - metasome: The posterior of the two or three main divisions of the body of certain invertebrates.
