### ISSUE TITLE
NTR: Request for S12 tarsus

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#16]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>tarsus <p><b>Definition</b><p> The bones or cartilages of the part of the foot between the metatarsus and the leg; also the foot of an insect or a crustacean, usually consisting of two to five joints.<p><H2> Optional </H2><p>

**Comment by roswri** [comment]
Term created:
S1273 - tarsus: The bones or cartilages of the part of the foot between the metatarsus and the leg; also the foot of an insect or a crustacean, usually consisting of two to five joints.
