### ISSUE TITLE
NTR: Request for S12 wings

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#17]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>wings <p><b>Definition</b><p> Paired structures which certain animals use to propel themselves in the air or water.<p><H2> Optional </H2><p>

**Comment by roswri** [comment]
Term created:
Made singular as per advice in new s12 SQL menu.
S1274 - wing: A structure, usually paired, which certain animals use to propel themselves in the air or water.
