### ISSUE TITLE
NTR: Request for S12 central disc (BODCNVS-1115)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#18]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>central disc <p><b>Definition</b><p> The central body part of a starfish (Asteroidea) also known as sea star, containing the internal organs, and the mouth and anus, and from which arms arms radiate. The radius of the central disc is used as a standard biometric measurement in starfish studies.<p><H2> Optional </H2><p><b>Sources/references</b><p> multiple online resourceshttps://github.com/nvs-vocabs/P01/issues/74 (BODCNVS-1115)<p>

**Comment by gwemon** [comment]
New code created and queued for publication on the NVS 
S1275	central disc
