### ISSUE TITLE
NTR: Request for S12 starfish arm

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#19]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>starfish arm <p><b>Definition</b><p> One of generally five (but in some species more) appendages of a starfish (also known as sea stars) that radiate from the central disc.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://en.wikipedia.org/wiki/Starfishhttps://github.com/nvs-vocabs/P01/issues/73<p>

**Comment by gwemon** [comment]
We would not normally specify the type of organism to which the body part belong in S12 however, the term "arm" can be applied to so many different types of organisms with different degree of precision (e.g. arm vs forearm vs leg vs tentacle) that I exceptionally decided to specify "starfish arm". The term is requested as part of standard starfish biometric measurements to be used in the OBIS schema where the biological entity is not identified in the P01 code but in a different field in the data schema. For this reason and to avoid creating a combined P01 label that would could be used inappropriately I opted to be specific. We can review this decision at a later stage if this creates issues.

**Comment by gwemon** [comment]
New term added to S12 with identifier S1276. Queued for publication on the NVS.

**Comment by gwemon** [comment]
https://vocab.nerc.ac.uk/collection/S12/current/S1276/
