### ISSUE TITLE
NTR: Request for S12 muscle tissues and gonads (BODCNVS-1088)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#20]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>muscle tissues and gonads <p><b>Definition</b><p> Muscles and gonads considered as one entity.<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-1088, SIMM vocabs<p>

**Comment by gwemon** [comment]
Term S1282 queued for publication on the NVS.

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S12/current/S1282/
