### ISSUE TITLE
NTR: Request for S12 host tissue

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#21]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>host tissue <p><b>Definition</b><p> The soft tissue component of the host organism in a symbiotic (mutualistic, commensalistic, or parasitic) relationship.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/ereefs/issues/10<p>

**Comment by gwemon** [comment]
@roswri I need to think about the consequence of having "host" + "tissue" in S12.

**Comment by gwemon** [comment]
@roswri  actually now that I see your S25 compilation I think that it makes sense to have "host tissue" as a subcomponent concept in S12.

**Comment by roswri** [comment]
Thanks @gwemon,

Are you happy for me to create this with the definition specified?

**Comment by gwemon** [comment]
yes all good @roswri

**Comment by roswri** [comment]
Term created:
S1277 - host tissue

**Comment by roswri** [comment]
Term now live on the NVS:
http://vocab.nerc.ac.uk/collection/S12/current/S1277/
