### ISSUE TITLE
NTR: Request for S12 brown meat

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#23]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>brown meat <p><b>Definition</b><p> A term used to refer to the flesh of crabs extracted from the main body cavity and consisting of the hepatopancreas (digestive gland) and reproductive organs.<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-1408<p>

**Comment by gwemon** [comment]
Term S1281 created and queued for publication on the NVS.

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S12/current/S1281/
