### ISSUE TITLE
NTR: Request for S12 structural cellular components

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#24]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>structural cellular components <p><b>Definition</b><p> The physical parts of a cell including the cell wall (if present), cell membrane, nucleus, and other organelles.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/ereefs/issues/17<p>

**Comment by roswri** [comment]
Term created:
S1280 - structural cellular components

**Comment by roswri** [comment]
published to NVS:
http://vocab.nerc.ac.uk/collection/S12/current/S1280/
