### ISSUE TITLE
NTR: Request for S12 intracellular reserve pool

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#25]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>intracellular reserve pool <p><b>Definition</b><p> The stored nutrients within a cell or organism.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/ereefs/issues/17<p>

**Comment by roswri** [comment]
adjusted definition:
A quantity of a substance, for example nutrients or neurotransmitters, stored within a cell, part of a cell, or an organism.

**Comment by gwemon** [comment]
@roswri How about "The sum of substances (nutrients, neurotransmitters) which are present within a biological cell in a storage capacity."? Feel free to adapt.

**Comment by roswri** [comment]
Term created:
S1283 - intracellular reserve pool

**Comment by roswri** [comment]
Term published to NVS:
http://vocab.nerc.ac.uk/collection/S12/current/S1283/
