### ISSUE TITLE
NTR: Request for S12 siphosome

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#26]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>siphosome <p><b>Definition</b><p> The main stem of the nectosome which contains feeding, reproductive, defensive and buoyant zooids.<p><H2> Optional </H2><p>

**Comment by jakjonbodc** [comment]
https://github.com/nvs-vocabs/P01/issues/209

**Comment by jakjonbodc** [comment]
https://www.nhm.ac.uk/our-science/departments-and-staff/staff-directory/gill-mapstone.html

**Comment by gwemon** [comment]
We could say: "Stem of a siphonophore colony to which feeding, reproductive, defensive and buoyant zooid units are attached."

**Comment by jakjonbodc** [comment]
S12 term created for siphosome - S1285

**Comment by gwemon** [comment]
Live on the NVS: http://vocab.nerc.ac.uk/collection/S12/current/S1285/
