### ISSUE TITLE
NTR: Request for S12 sea mat

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#27]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>sea mat <p><b>Definition</b><p> A flat colony of zooids<p><H2> Optional </H2><p>

**Comment by jakjonbodc** [comment]
https://github.com/nvs-vocabs/P01/issues/209

**Comment by jakjonbodc** [comment]
https://www.wildlifetrusts.org/wildlife-explorer/marine/colonial-creatures/sea-mat

**Comment by jakjonbodc** [comment]
After discussion, 'Bryozoan sea mat' will be defined as a txnam in smbioent rather than adding 'sea mat' to the existing Bryozoa term. This is because 'Bryozoan sea mat' is what is known to the wider community and what they will search for.
