### ISSUE TITLE
NTR: Request for S12 stipe (BODCNVS-1232)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#28]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>stipe <p><b>Definition</b><p> The stalk or stem of plants (including macroalgae) and fungi.<p><H2> Optional </H2><p>

**Comment by gwemon** [comment]
Linked to https://github.com/nvs-vocabs/P01/issues/238

**Comment by gwemon** [comment]
This term and its URI http://vocab.nerc.ac.uk/collection/S12/current/S1286/ are now live in the NVS.
