### ISSUE TITLE
NTR: Request for S12 nectophores

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#3]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>nectophores <p><b>Definition</b><p> Also known as "swimming bells", nectophores are medusae that are specialized for moving a physonect siphonophore colony through the water. The region of the colony containing the nectophores is called the nectosome.<p><H2> Optional </H2><p><b>ORCID</b><p> gwemon<p>

**Comment by gwemon** [comment]
Code S1260 queued for publication

**Comment by danibodc** [comment]
This term is available at: https://vocab.nerc.ac.uk/collection/S12/current/S1260/
