### ISSUE TITLE
NTR: Request for S12 bell

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#5]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>bell <p><b>Definition</b><p> The umbrella-shaped body part of a medusozoan Cnidaria (jellyfish). It can pulsate to provide propulsion.<p><H2> Optional </H2><p><b>Sources/references</b><p> mixed<p>

**Comment by gwemon** [comment]
Relates to https://github.com/nvs-vocabs/P01/issues/78

**Comment by roswri** [comment]
Term created:
S1263 - bell: The umbrella-shaped body part of a medusozoan Cnidaria (jellyfish). It can pulsate to provide propulsion.
