### ISSUE TITLE
NTR: Request for S12 shoot

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#7]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>shoot <p><b>Definition</b><p> Above ground part of plants consisting of any plant stem together with its appendages, leaves and lateral buds, flowering stems, and flower buds.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://en.wikipedia.org/wiki/Shoot and seagrass anatomy descriptions<p>

**Comment by roswri** [comment]
Term created:
S1264  - shoot: Above ground part of plants consisting of any plant stem together with its appendages, leaves and lateral buds, flowering stems, and flower buds.
