### ISSUE TITLE
NTR: Request for S12 carapace

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#8]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>carapace <p><b>Definition</b><p> Bony or chitinous case or shield covering the back or part of the back of some animals turtles or crabs.<p><H2> Optional </H2><p><b>Sources/references</b><p> multiple<p> <b>Mapping to other terminologies </b><p> http://vocab.nerc.ac.uk/collection/P21/current/MS1757/ (sameAs)http://purl.obolibrary.org/obo/UBERON_0008275<p>

**Comment by roswri** [comment]
Term created:
S1265 - carapace: Bony or chitinous case or shield covering the back or part of the back of some animals like turtles or crabs.
